Use "File.exist?" Instead of "File.exists?"
"File.exists?" is deprecated as of Ruby 3.2

```
NoMethodError: undefined method `exists?' for File:Class
/Users/yosi/.rvm/gems/ruby-3.2.0/gems/otr-activerecord-2.1.1/lib/tasks/otr-activerecord.rake:63:in `block (3 levels) in <top (required)>'
/Users/yosi/.rvm/gems/ruby-3.2.0/gems/otr-activerecord-2.1.1/lib/tasks/otr-activerecord.rake:62:in `each'
```